-- MySQL Script generated by MySQL Workbench
-- Sat Aug 13 13:10:38 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Farmacia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Farmacia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Farmacia` DEFAULT CHARACTER SET utf8 ;
USE `Farmacia` ;

-- -----------------------------------------------------
-- Table `Farmacia`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmacia`.`clientes` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(45) NOT NULL,
  `cpfCliente` VARCHAR(45) NOT NULL,
  `telCliente` VARCHAR(45) NOT NULL,
  `emailCliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farmacia`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmacia`.`compras` (
  `notaFiscal` DOUBLE NOT NULL,
  `dataCompra` VARCHAR(45) NOT NULL,
  `valorTotal` DOUBLE NOT NULL,
  `clientes_idCliente` INT NOT NULL,
  PRIMARY KEY (`notaFiscal`),
  INDEX `fk_compras_clientes1_idx` (`clientes_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_compras_clientes1`
    FOREIGN KEY (`clientes_idCliente`)
    REFERENCES `Farmacia`.`clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farmacia`.`endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmacia`.`endereço` (
  `rua` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `clientes_idCliente` INT NOT NULL,
  INDEX `fk_endereço_clientes_idx` (`clientes_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_endereço_clientes`
    FOREIGN KEY (`clientes_idCliente`)
    REFERENCES `Farmacia`.`clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farmacia`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmacia`.`Produtos` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nomeProduto` VARCHAR(45) NOT NULL,
  `precoProduto` DOUBLE NOT NULL,
  `flag_generico` VARCHAR(3) NOT NULL,
  `estoqueProduto` INT NOT NULL,
  `flag_Remedio` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farmacia`.`itensVendidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmacia`.`itensVendidos` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `qtd` INT NOT NULL,
  `preçoProduto` DOUBLE NOT NULL,
  `preçoFinal` DOUBLE NOT NULL,
  `preçoDesconto` DOUBLE NULL,
  `compras_notaFiscal` DOUBLE NOT NULL,
  `Produtos_idProduto` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_itensVendidos_compras1_idx` (`compras_notaFiscal` ASC) VISIBLE,
  INDEX `fk_itensVendidos_Produtos1_idx` (`Produtos_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_itensVendidos_compras1`
    FOREIGN KEY (`compras_notaFiscal`)
    REFERENCES `Farmacia`.`compras` (`notaFiscal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itensVendidos_Produtos1`
    FOREIGN KEY (`Produtos_idProduto`)
    REFERENCES `Farmacia`.`Produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
